// 場面（タブ）の一覧です。並び順がそのまま画面の並び順になります。
const SCENES = [
  {
    id: "greetings",
    title: "あいさつ",
    subtitle: "基本の会話",
    icon: "👋",
    lead: "お店や道端でまず使う言葉です。困ったら「請問（チンウェン）」から話しかけましょう。",
  },
  {
    id: "restaurant",
    title: "レストラン",
    subtitle: "注文と会計",
    icon: "🍜",
    lead: "夜市・食堂・ドリンクスタンドでそのまま使えます。",
  },
  {
    id: "transport",
    title: "交通",
    subtitle: "MRT・バス・タクシー",
    icon: "🚇",
    lead: "行き先を伝えるときや、乗り方を聞くときに使います。",
  },
  {
    id: "shopping",
    title: "買い物",
    subtitle: "値段と支払い",
    icon: "🛍️",
    lead: "夜市やお店でのやりとりに使います。台湾ではレジ袋が有料のことが多いです。",
  },
  {
    id: "hotel",
    title: "ホテル",
    subtitle: "チェックイン・困りごと",
    icon: "🏨",
    lead: "フロントでのやりとりや、部屋で困ったときに使います。",
  },
  {
    id: "emergency",
    title: "緊急時",
    subtitle: "体調不良・盗難",
    icon: "🚨",
    lead: "台湾の緊急電話：110（警察）、119（救急車・消防）。落ち着いて「見せる」ボタンで画面を相手に見せましょう。",
  },
];

// 各フレーズ：zh＝台湾で使う繁体字、pinyin＝拼音、kana＝カタカナ読み（目安）、ja＝日本語訳
const PHRASES = {
  greetings: [
    { zh: "你好", pinyin: "Nǐ hǎo", kana: "ニー ハオ", ja: "こんにちは" },
    { zh: "早安", pinyin: "Zǎo'ān", kana: "ザオ アン", ja: "おはようございます" },
    { zh: "晚安", pinyin: "Wǎn'ān", kana: "ワン アン", ja: "おやすみなさい" },
    { zh: "謝謝", pinyin: "Xièxie", kana: "シェシェ", ja: "ありがとう" },
    { zh: "非常感謝", pinyin: "Fēicháng gǎnxiè", kana: "フェイチャン ガンシエ", ja: "本当にありがとうございます" },
    { zh: "不客氣", pinyin: "Bú kèqì", kana: "ブー クーチー", ja: "どういたしまして" },
    { zh: "對不起", pinyin: "Duìbuqǐ", kana: "ドゥイ ブ チー", ja: "ごめんなさい" },
    { zh: "不好意思", pinyin: "Bù hǎoyìsi", kana: "ブー ハオイース", ja: "すみません（声をかけるとき・軽く謝るとき）" },
    { zh: "沒關係", pinyin: "Méi guānxi", kana: "メイ グアンシ", ja: "大丈夫です／気にしないで" },
    { zh: "請問", pinyin: "Qǐngwèn", kana: "チンウェン", ja: "ちょっとお尋ねします" },
    { zh: "好的", pinyin: "Hǎo de", kana: "ハオ ダ", ja: "わかりました／はい" },
    { zh: "不用了，謝謝", pinyin: "Bú yòng le, xièxie", kana: "ブー ヨン ラ、シェシェ", ja: "結構です、ありがとう" },
    { zh: "我是日本人", pinyin: "Wǒ shì Rìběnrén", kana: "ウォー シー リーベンレン", ja: "私は日本人です" },
    { zh: "我會說一點中文", pinyin: "Wǒ huì shuō yìdiǎn Zhōngwén", kana: "ウォー フイ シュオ イーディエン ジョンウェン", ja: "中国語が少し話せます" },
    { zh: "我聽不懂", pinyin: "Wǒ tīng bù dǒng", kana: "ウォー ティン ブー ドン", ja: "聞き取れません" },
    { zh: "請再說一次", pinyin: "Qǐng zài shuō yí cì", kana: "チン ザイ シュオ イー ツー", ja: "もう一度言ってください" },
    { zh: "請說慢一點", pinyin: "Qǐng shuō màn yìdiǎn", kana: "チン シュオ マン イーディエン", ja: "もう少しゆっくり話してください" },
    { zh: "可以寫給我看嗎？", pinyin: "Kěyǐ xiě gěi wǒ kàn ma?", kana: "クーイー シエ ゲイ ウォー カン マ", ja: "書いて見せてもらえますか？" },
    { zh: "你會說英文嗎？", pinyin: "Nǐ huì shuō Yīngwén ma?", kana: "ニー フイ シュオ インウェン マ", ja: "英語は話せますか？" },
    { zh: "廁所在哪裡？", pinyin: "Cèsuǒ zài nǎlǐ?", kana: "ツァースオ ザイ ナーリー", ja: "トイレはどこですか？" },
    { zh: "可以幫我拍照嗎？", pinyin: "Kěyǐ bāng wǒ pāizhào ma?", kana: "クーイー バン ウォー パイジャオ マ", ja: "写真を撮ってもらえますか？" },
    { zh: "再見", pinyin: "Zàijiàn", kana: "ザイジエン", ja: "さようなら" },
  ],
  restaurant: [
    { zh: "我們兩個人", pinyin: "Wǒmen liǎng ge rén", kana: "ウォーメン リャン ガ レン", ja: "2人です" },
    { zh: "有位子嗎？", pinyin: "Yǒu wèizi ma?", kana: "ヨウ ウェイズ マ", ja: "席は空いていますか？" },
    { zh: "請給我菜單", pinyin: "Qǐng gěi wǒ càidān", kana: "チン ゲイ ウォー ツァイダン", ja: "メニューをください" },
    { zh: "有日文菜單嗎？", pinyin: "Yǒu Rìwén càidān ma?", kana: "ヨウ リーウェン ツァイダン マ", ja: "日本語のメニューはありますか？" },
    { zh: "有推薦的嗎？", pinyin: "Yǒu tuījiàn de ma?", kana: "ヨウ トゥイジエン ダ マ", ja: "おすすめはありますか？" },
    { zh: "我要這個", pinyin: "Wǒ yào zhège", kana: "ウォー ヤオ ジェイガ", ja: "これをください" },
    { zh: "我要一份", pinyin: "Wǒ yào yí fèn", kana: "ウォー ヤオ イー フェン", ja: "1人前ください" },
    { zh: "內用", pinyin: "Nèiyòng", kana: "ネイヨン", ja: "店内で食べます" },
    { zh: "外帶", pinyin: "Wàidài", kana: "ワイダイ", ja: "持ち帰りです" },
    { zh: "不要辣", pinyin: "Bú yào là", kana: "ブー ヤオ ラー", ja: "辛くしないでください" },
    { zh: "小辣就好", pinyin: "Xiǎo là jiù hǎo", kana: "シアオ ラー ジウ ハオ", ja: "少し辛いくらいでお願いします" },
    { zh: "不要香菜", pinyin: "Bú yào xiāngcài", kana: "ブー ヤオ シアンツァイ", ja: "パクチーを入れないでください" },
    { zh: "我對花生過敏", pinyin: "Wǒ duì huāshēng guòmǐn", kana: "ウォー ドゥイ ホアシェン グオミン", ja: "ピーナッツアレルギーがあります" },
    { zh: "我吃素", pinyin: "Wǒ chī sù", kana: "ウォー チー スー", ja: "私はベジタリアンです" },
    { zh: "半糖少冰", pinyin: "Bàn táng shǎo bīng", kana: "バン タン シャオ ビン", ja: "甘さ半分、氷少なめで（ドリンク）" },
    { zh: "去冰", pinyin: "Qù bīng", kana: "チュー ビン", ja: "氷なしで（ドリンク）" },
    { zh: "請給我一杯水", pinyin: "Qǐng gěi wǒ yì bēi shuǐ", kana: "チン ゲイ ウォー イー ベイ シュイ", ja: "お水を一杯ください" },
    { zh: "很好吃", pinyin: "Hěn hǎochī", kana: "ヘン ハオチー", ja: "とてもおいしいです" },
    { zh: "請幫我打包", pinyin: "Qǐng bāng wǒ dǎbāo", kana: "チン バン ウォー ダーバオ", ja: "（残りを）持ち帰り用に包んでください" },
    { zh: "我要結帳", pinyin: "Wǒ yào jiézhàng", kana: "ウォー ヤオ ジエジャン", ja: "お会計をお願いします" },
    { zh: "可以刷卡嗎？", pinyin: "Kěyǐ shuākǎ ma?", kana: "クーイー シュアカー マ", ja: "カードで払えますか？" },
  ],
  transport: [
    { zh: "捷運站在哪裡？", pinyin: "Jiéyùn zhàn zài nǎlǐ?", kana: "ジエユン ジャン ザイ ナーリー", ja: "MRT（地下鉄）の駅はどこですか？" },
    { zh: "火車站怎麼走？", pinyin: "Huǒchēzhàn zěnme zǒu?", kana: "フオチャージャン ゼンマ ゾウ", ja: "鉄道の駅へはどう行けばいいですか？" },
    { zh: "公車站在哪裡？", pinyin: "Gōngchē zhàn zài nǎlǐ?", kana: "ゴンチャー ジャン ザイ ナーリー", ja: "バス停はどこですか？" },
    { zh: "走路可以到嗎？", pinyin: "Zǒulù kěyǐ dào ma?", kana: "ゾウルー クーイー ダオ マ", ja: "歩いて行けますか？" },
    { zh: "要多久？", pinyin: "Yào duō jiǔ?", kana: "ヤオ ドゥオ ジウ", ja: "どのくらい時間がかかりますか？" },
    { zh: "我要買票", pinyin: "Wǒ yào mǎi piào", kana: "ウォー ヤオ マイ ピャオ", ja: "切符を買いたいです" },
    { zh: "一張到台南的票", pinyin: "Yì zhāng dào Táinán de piào", kana: "イー ジャン ダオ タイナン ダ ピャオ", ja: "台南までの切符を1枚ください" },
    { zh: "這班車到機場嗎？", pinyin: "Zhè bān chē dào jīchǎng ma?", kana: "ジェ バン チャー ダオ ジーチャン マ", ja: "この電車（バス）は空港に行きますか？" },
    { zh: "下一班是幾點？", pinyin: "Xià yì bān shì jǐ diǎn?", kana: "シア イー バン シー ジー ディエン", ja: "次の便は何時ですか？" },
    { zh: "要在哪裡換車？", pinyin: "Yào zài nǎlǐ huàn chē?", kana: "ヤオ ザイ ナーリー ホアン チャー", ja: "どこで乗り換えればいいですか？" },
    { zh: "可以用悠遊卡嗎？", pinyin: "Kěyǐ yòng Yōuyóukǎ ma?", kana: "クーイー ヨン ヨウヨウカー マ", ja: "悠遊カード（EasyCard）は使えますか？" },
    { zh: "出口在哪裡？", pinyin: "Chūkǒu zài nǎlǐ?", kana: "チューコウ ザイ ナーリー", ja: "出口はどこですか？" },
    { zh: "請幫我叫計程車", pinyin: "Qǐng bāng wǒ jiào jìchéngchē", kana: "チン バン ウォー ジャオ ジーチョンチャー", ja: "タクシーを呼んでください" },
    { zh: "請到台北車站", pinyin: "Qǐng dào Táiběi Chēzhàn", kana: "チン ダオ タイベイ チャージャン", ja: "台北駅までお願いします" },
    { zh: "請到這個地址", pinyin: "Qǐng dào zhège dìzhǐ", kana: "チン ダオ ジェイガ ディージー", ja: "この住所までお願いします" },
    { zh: "請到這家飯店", pinyin: "Qǐng dào zhè jiā fàndiàn", kana: "チン ダオ ジェ ジア ファンディエン", ja: "このホテルまでお願いします" },
    { zh: "請在這裡停", pinyin: "Qǐng zài zhèlǐ tíng", kana: "チン ザイ ジェリー ティン", ja: "ここで停めてください" },
    { zh: "請開後車廂", pinyin: "Qǐng kāi hòu chēxiāng", kana: "チン カイ ホウ チャーシアン", ja: "トランクを開けてください" },
  ],
  shopping: [
    { zh: "這個多少錢？", pinyin: "Zhège duōshǎo qián?", kana: "ジェイガ ドゥオシャオ チエン", ja: "これはいくらですか？" },
    { zh: "我只是看看", pinyin: "Wǒ zhǐshì kànkan", kana: "ウォー ジーシー カンカン", ja: "見ているだけです" },
    { zh: "可以便宜一點嗎？", pinyin: "Kěyǐ piányí yìdiǎn ma?", kana: "クーイー ピエンイー イーディエン マ", ja: "少し安くなりますか？" },
    { zh: "太貴了", pinyin: "Tài guì le", kana: "タイ グイ ラ", ja: "高すぎます" },
    { zh: "可以試吃嗎？", pinyin: "Kěyǐ shìchī ma?", kana: "クーイー シーチー マ", ja: "試食できますか？" },
    { zh: "可以試穿嗎？", pinyin: "Kěyǐ shìchuān ma?", kana: "クーイー シーチュアン マ", ja: "試着できますか？" },
    { zh: "有別的顏色嗎？", pinyin: "Yǒu bié de yánsè ma?", kana: "ヨウ ビエ ダ イエンサー マ", ja: "ほかの色はありますか？" },
    { zh: "有大一號的嗎？", pinyin: "Yǒu dà yí hào de ma?", kana: "ヨウ ダー イー ハオ ダ マ", ja: "1つ大きいサイズはありますか？" },
    { zh: "有小一號的嗎？", pinyin: "Yǒu xiǎo yí hào de ma?", kana: "ヨウ シアオ イー ハオ ダ マ", ja: "1つ小さいサイズはありますか？" },
    { zh: "我要兩個", pinyin: "Wǒ yào liǎng ge", kana: "ウォー ヤオ リャン ガ", ja: "2つください" },
    { zh: "我買這個", pinyin: "Wǒ mǎi zhège", kana: "ウォー マイ ジェイガ", ja: "これを買います" },
    { zh: "只收現金嗎？", pinyin: "Zhǐ shōu xiànjīn ma?", kana: "ジー ショウ シエンジン マ", ja: "現金のみですか？" },
    { zh: "可以刷卡嗎？", pinyin: "Kěyǐ shuākǎ ma?", kana: "クーイー シュアカー マ", ja: "カードで払えますか？" },
    { zh: "請給我袋子", pinyin: "Qǐng gěi wǒ dàizi", kana: "チン ゲイ ウォー ダイズ", ja: "袋をください" },
    { zh: "不用袋子", pinyin: "Bú yòng dàizi", kana: "ブー ヨン ダイズ", ja: "袋はいりません" },
    { zh: "可以幫我包起來嗎？", pinyin: "Kěyǐ bāng wǒ bāo qǐlái ma?", kana: "クーイー バン ウォー バオ チーライ マ", ja: "包装してもらえますか？" },
    { zh: "請給我收據", pinyin: "Qǐng gěi wǒ shōujù", kana: "チン ゲイ ウォー ショウジュー", ja: "レシートをください" },
    { zh: "可以退稅嗎？", pinyin: "Kěyǐ tuìshuì ma?", kana: "クーイー トゥイシュイ マ", ja: "免税（タックスフリー）はできますか？" },
  ],
  hotel: [
    { zh: "我要辦理入住", pinyin: "Wǒ yào bànlǐ rùzhù", kana: "ウォー ヤオ バンリー ルージュー", ja: "チェックインをお願いします" },
    { zh: "我有預約", pinyin: "Wǒ yǒu yùyuē", kana: "ウォー ヨウ ユーユエ", ja: "予約しています" },
    { zh: "這是我的護照", pinyin: "Zhè shì wǒ de hùzhào", kana: "ジェ シー ウォー ダ フージャオ", ja: "これが私のパスポートです" },
    { zh: "幾點可以入住？", pinyin: "Jǐ diǎn kěyǐ rùzhù?", kana: "ジー ディエン クーイー ルージュー", ja: "何時からチェックインできますか？" },
    { zh: "可以先寄放行李嗎？", pinyin: "Kěyǐ xiān jìfàng xínglǐ ma?", kana: "クーイー シエン ジーファン シンリー マ", ja: "先に荷物を預けられますか？" },
    { zh: "早餐幾點開始？", pinyin: "Zǎocān jǐ diǎn kāishǐ?", kana: "ザオツァン ジー ディエン カイシー", ja: "朝食は何時からですか？" },
    { zh: "早餐在哪裡吃？", pinyin: "Zǎocān zài nǎlǐ chī?", kana: "ザオツァン ザイ ナーリー チー", ja: "朝食はどこで食べられますか？" },
    { zh: "無線網路的密碼是什麼？", pinyin: "Wúxiàn wǎnglù de mìmǎ shì shénme?", kana: "ウーシエン ワンルー ダ ミーマー シー シェンマ", ja: "Wi-Fiのパスワードは何ですか？" },
    { zh: "冷氣壞了", pinyin: "Lěngqì huài le", kana: "ロンチー ホアイ ラ", ja: "エアコンが壊れています" },
    { zh: "沒有熱水", pinyin: "Méiyǒu rèshuǐ", kana: "メイヨウ ラーシュイ", ja: "お湯が出ません" },
    { zh: "可以換房間嗎？", pinyin: "Kěyǐ huàn fángjiān ma?", kana: "クーイー ホアン ファンジエン マ", ja: "部屋を替えてもらえますか？" },
    { zh: "請再給我一條毛巾", pinyin: "Qǐng zài gěi wǒ yì tiáo máojīn", kana: "チン ザイ ゲイ ウォー イー ティアオ マオジン", ja: "タオルをもう1枚ください" },
    { zh: "我把房卡忘在房間裡了", pinyin: "Wǒ bǎ fángkǎ wàng zài fángjiān lǐ le", kana: "ウォー バー ファンカー ワン ザイ ファンジエン リー ラ", ja: "カードキーを部屋に置き忘れました" },
    { zh: "附近有便利商店嗎？", pinyin: "Fùjìn yǒu biànlì shāngdiàn ma?", kana: "フージン ヨウ ビエンリー シャンディエン マ", ja: "近くにコンビニはありますか？" },
    { zh: "我要退房", pinyin: "Wǒ yào tuìfáng", kana: "ウォー ヤオ トゥイファン", ja: "チェックアウトをお願いします" },
    { zh: "可以晚一點退房嗎？", pinyin: "Kěyǐ wǎn yìdiǎn tuìfáng ma?", kana: "クーイー ワン イーディエン トゥイファン マ", ja: "チェックアウトを少し遅くできますか？" },
    { zh: "退房後可以寄放行李嗎？", pinyin: "Tuìfáng hòu kěyǐ jìfàng xínglǐ ma?", kana: "トゥイファン ホウ クーイー ジーファン シンリー マ", ja: "チェックアウト後に荷物を預けられますか？" },
  ],
  emergency: [
    { zh: "救命啊！", pinyin: "Jiùmìng a!", kana: "ジウミン ア", ja: "助けて！" },
    { zh: "請幫幫我", pinyin: "Qǐng bāngbang wǒ", kana: "チン バンバン ウォー", ja: "手伝ってください" },
    { zh: "請叫救護車", pinyin: "Qǐng jiào jiùhùchē", kana: "チン ジャオ ジウフーチャー", ja: "救急車を呼んでください" },
    { zh: "請叫警察", pinyin: "Qǐng jiào jǐngchá", kana: "チン ジャオ ジンチャー", ja: "警察を呼んでください" },
    { zh: "我身體不舒服", pinyin: "Wǒ shēntǐ bù shūfu", kana: "ウォー シェンティー ブー シューフ", ja: "体の具合が悪いです" },
    { zh: "我這裡很痛", pinyin: "Wǒ zhèlǐ hěn tòng", kana: "ウォー ジェリー ヘン トン", ja: "ここが痛いです" },
    { zh: "我肚子痛", pinyin: "Wǒ dùzi tòng", kana: "ウォー ドゥーズ トン", ja: "お腹が痛いです" },
    { zh: "我發燒了", pinyin: "Wǒ fāshāo le", kana: "ウォー ファーシャオ ラ", ja: "熱があります" },
    { zh: "我有過敏", pinyin: "Wǒ yǒu guòmǐn", kana: "ウォー ヨウ グオミン", ja: "アレルギーがあります" },
    { zh: "醫院在哪裡？", pinyin: "Yīyuàn zài nǎlǐ?", kana: "イーユエン ザイ ナーリー", ja: "病院はどこですか？" },
    { zh: "附近有藥局嗎？", pinyin: "Fùjìn yǒu yàojú ma?", kana: "フージン ヨウ ヤオジュー マ", ja: "近くに薬局はありますか？" },
    { zh: "我迷路了", pinyin: "Wǒ mílù le", kana: "ウォー ミールー ラ", ja: "道に迷いました" },
    { zh: "請帶我去這裡", pinyin: "Qǐng dài wǒ qù zhèlǐ", kana: "チン ダイ ウォー チュー ジェリー", ja: "ここへ連れて行ってください" },
    { zh: "我的護照不見了", pinyin: "Wǒ de hùzhào bú jiàn le", kana: "ウォー ダ フージャオ ブー ジエン ラ", ja: "パスポートをなくしました" },
    { zh: "我的錢包被偷了", pinyin: "Wǒ de qiánbāo bèi tōu le", kana: "ウォー ダ チエンバオ ベイ トウ ラ", ja: "財布を盗まれました" },
    { zh: "我需要日文翻譯", pinyin: "Wǒ xūyào Rìwén fānyì", kana: "ウォー シューヤオ リーウェン ファンイー", ja: "日本語の通訳が必要です" },
    { zh: "請聯絡日本台灣交流協會", pinyin: "Qǐng liánluò Rìběn Táiwān Jiāoliú Xiéhuì", kana: "チン リエンルオ リーベン タイワン ジアオリウ シエフイ", ja: "日本台湾交流協会（日本の窓口）に連絡してください" },
  ],
};
